### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by wayne-chen** [vstadnytskyi/circular_buffer_numpy#5]
https://github.com/vstadnytskyi/circular_buffer_numpy/blob/1bf661bceed3f8ac46f7b4741ad297d42e4c7d7d/circular_buffer_numpy/circular_buffer.py#L67

Seems to be a typo that was reflected in the hosted docs.

**Comment by vstadnytskyi** [comment]
@wayne-chen Thank you. Fixed.
